export interface Deal {
  id: number;
  product: string;
  year: number;
  price: number | null;
  priceDisplay: string;
  msrp: number | null;
  seller: string;
  url: string;
  listingType: 'buy_now' | 'auction' | 'sold_out' | 'reference';
  availability: 'in_stock' | 'sold_out' | 'unknown' | 'auction';
  category: 'sealed_box' | 'single' | 'case' | 'break' | 'other';
  notes: string;
  source: string;
  highlight: 'hot_deal' | 'below_msrp' | 'watch' | 'sold_out' | 'premium_single' | null;
  dateFound: string;
}

export const deals: Deal[] = [
  // ── HOT DEALS (In Stock, Good Prices) ──────────────────────────────

  {
    id: 1,
    product: '2025 Topps Chrome F1 Hobby Box',
    year: 2025,
    price: 349.95,
    priceDisplay: '$349.95',
    msrp: 250,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2025-topps-chrome-formula-1-f1-racing-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $449.95 — competitive with major retailers. Free shipping over $199.',
    source: 'Steel City Collectibles',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 2,
    product: '2025 Topps Chrome F1 Hobby Box',
    year: 2025,
    price: 349.95,
    priceDisplay: '$349.95',
    msrp: 250,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2025-topps-chrome-formula-1-racing-hobby-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $399.95. Includes special 75th Anniversary pack (21 total). Free shipping over $299.',
    source: 'Blowout Cards',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 3,
    product: '2025 Topps Chrome F1 Hobby Box',
    year: 2025,
    price: 349.95,
    priceDisplay: '$349.95',
    msrp: 250,
    seller: "Dave & Adam's Card World",
    url: 'https://www.dacardworld.com/sports-cards/2025-topps-chrome-f1-formula-1-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Current market price. Free shipping over $199. Check for $25 off coupon for new sign-ups.',
    source: "Dave & Adam's",
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 4,
    product: '2025 Topps Chrome F1 Hobby Box',
    year: 2025,
    price: 350,
    priceDisplay: '$350.00',
    msrp: 250,
    seller: 'RbiCru7 Collectibles',
    url: 'https://rbicru7.com/products/2025-topps-chrome-formula-1-racing-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $375. 5 available. Competitive with major retailers.',
    source: 'RbiCru7 Collectibles',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 5,
    product: '2021 Topps Chrome F1 Hobby Box',
    year: 2021,
    price: 244.95,
    priceDisplay: '$244.95',
    msrp: null,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2021-topps-chrome-formula-1-racing-hobby-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $274.95. Key Hamilton/Verstappen rivalry year. 18 packs, 4 cards per pack.',
    source: 'Blowout Cards',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 6,
    product: '2021 Topps F1 Hobby Box (Paper)',
    year: 2021,
    price: 99.99,
    priceDisplay: '$99.99',
    msrp: null,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2021-topps-formula-1-racing-hobby-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Budget entry — Paper, not Chrome. 18 packs, 8 cards per pack. F1 relics with race-worn suits.',
    source: 'Blowout Cards',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 7,
    product: '2024 Topps Chrome F1 Qualifying Lap Box',
    year: 2024,
    price: 63.99,
    priceDisplay: '$63.99',
    msrp: 75,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2024-topps-chrome-formula-1-racing-qualifying-lap-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $74.95. 16 packs, 4 cards per pack. 4 exclusive B&W RayWave parallels. Great entry product.',
    source: 'Blowout Cards',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 8,
    product: '2025 Topps Chrome F1 Value Blaster Box',
    year: 2025,
    price: 29.99,
    priceDisplay: '$29.99',
    msrp: 30,
    seller: 'Best Buy / Walmart / Target',
    url: 'https://www.bestbuy.com/product/2025-topps-chrome-f1-blaster-box/J3ZPGX2LZ3',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Retail MSRP at Best Buy. Exclusive RayWave parallels. eBay secondary avg ~$52. Check stores for availability.',
    source: 'Best Buy',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 9,
    product: '2025 Topps Chrome F1 Blaster Box (6-Pack)',
    year: 2025,
    price: 59.99,
    priceDisplay: '$59.99',
    msrp: 60,
    seller: 'Burbank Cards',
    url: 'https://burbankcards.com/products/2025-topps-chrome-formula-1-racing-blaster-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: '6 packs, 4 cards per pack. 2 exclusive inserts. Free delivery. Shop Pay installments available.',
    source: 'Burbank Cards',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },

  // ── BELOW MSRP OPPORTUNITIES ───────────────────────────────────────

  {
    id: 10,
    product: '2025 Topps Lights Out F1 Hobby Box',
    year: 2025,
    price: 309.95,
    priceDisplay: '$309.95',
    msrp: 560,
    seller: "Dave & Adam's Card World",
    url: 'https://www.dacardworld.com/sports-cards/2025-topps-lights-out-formula-1-f1-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Significant discount from $560 MSRP. UK Fanatics exclusive originally. Now available via US major retail.',
    source: "Dave & Adam's",
    highlight: 'below_msrp',
    dateFound: '2026-03-14',
  },
  {
    id: 11,
    product: '2024 Topps Chrome F1 Hobby Box',
    year: 2024,
    price: 180,
    priceDisplay: '$180 (LCS / eBay BIN)',
    msrp: 240,
    seller: 'eBay / Local Card Shops',
    url: 'https://www.ebay.com/sch/i.html?_nkw=2024+topps+chrome+formula+1+hobby+box+sealed&LH_BIN=1&LH_ItemCondition=1000&_sop=15',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Significant drop from $240 launch price. Available at many local card shops and eBay for $180. Solid value buy.',
    source: 'Reddit / eBay',
    highlight: 'below_msrp',
    dateFound: '2026-03-14',
  },
  {
    id: 12,
    product: '2024 Topps Chrome F1 Sapphire Edition Hobby Box',
    year: 2024,
    price: 451,
    priceDisplay: '$429–$499 (eBay)',
    msrp: 500,
    seller: 'eBay (multiple sellers)',
    url: 'https://www.ebay.com/sch/i.html?_nkw=2024+topps+chrome+sapphire+formula+1+hobby+box&LH_BIN=1&_sop=15',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'True MSRP was ~$280 at Topps EQL launch. Market average $440. eBay BIN range $429–$499.',
    source: 'eBay / SportsCardsPro',
    highlight: 'below_msrp',
    dateFound: '2026-03-14',
  },
  {
    id: 13,
    product: '2024 Topps Dynasty F1 Hobby Box',
    year: 2024,
    price: 1200,
    priceDisplay: '$1,200',
    msrp: 1200,
    seller: 'StockX',
    url: 'https://stockx.com/2024-topps-dynasty-formula-1-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'At MSRP on StockX. Last sale $1,200. Released Feb 7, 2025. All retailers OOS.',
    source: 'StockX',
    highlight: 'below_msrp',
    dateFound: '2026-03-14',
  },
  {
    id: 14,
    product: '2025 Topps Chrome F1 Hobby Box',
    year: 2025,
    price: 335,
    priceDisplay: '$335 (lowest ask)',
    msrp: 250,
    seller: 'StockX',
    url: 'https://stockx.com/2025-topps-chrome-formula-1-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'StockX lowest ask $335, last sale $315. Above MSRP but below retail. Market avg $335.',
    source: 'StockX',
    highlight: null,
    dateFound: '2026-03-14',
  },

  // ── SEALED BOXES IN STOCK ──────────────────────────────────────────

  {
    id: 15,
    product: '2024 Topps Chrome F1 Hobby Box',
    year: 2024,
    price: 349.95,
    priceDisplay: '$349.95',
    msrp: 240,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2024-topps-chrome-formula-1-racing-hobby-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'In stock but priced significantly above current eBay market ($180). Includes 12 packs, 8 cards/pack.',
    source: 'Blowout Cards',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 16,
    product: '2023 Topps Chrome F1 Hobby Box',
    year: 2023,
    price: 549.95,
    priceDisplay: '$549.95',
    msrp: null,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2023-topps-chrome-formula-1-racing-hobby-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $669.95 — save $120. Only 1 left! Features Piastri as top chase. Released Feb 2024.',
    source: 'Blowout Cards',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 17,
    product: '2022 Topps Chrome F1 Hobby Box',
    year: 2022,
    price: 349.95,
    priceDisplay: '$349.95',
    msrp: null,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2022-topps-chrome-formula-1-racing-hobby-box.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sale from $399.95. 18 packs, 4 cards per pack. Key Verstappen WDC defense year.',
    source: 'Blowout Cards',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 18,
    product: '2025 Topps Chrome F1 Hobby Box',
    year: 2025,
    price: 369.99,
    priceDisplay: '$369.99',
    msrp: 250,
    seller: 'Burbank Cards',
    url: 'https://burbankcards.com/products/2025-topps-chrome-formula-1-racing-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Shop Pay installments available. Higher than competitors but in stock.',
    source: 'Burbank Cards',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 19,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: 3099.95,
    priceDisplay: '$3,099.95',
    msrp: 1200,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2025-topps-dynasty-formula-1-f1-racing-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Premium ultra-high-end. Guaranteed 1 Premium Relic Auto. First-ever Senna inscription card. PayPal financing available.',
    source: 'Steel City Collectibles',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 20,
    product: '2025 Topps Chrome F1 Sapphire Edition Hobby Box',
    year: 2025,
    price: 914.95,
    priceDisplay: '$914.95',
    msrp: 500,
    seller: 'Giant Sports Cards',
    url: 'https://giantsportscards.com/products/2025-topps-chrome-f1-formula-one-sapphire-hobby-box',
    listingType: 'buy_now',
    availability: 'unknown',
    category: 'sealed_box',
    notes: 'Sale from $924.95. EQL launch was $449.99/box. Released Feb 12, 2026.',
    source: 'Giant Sports Cards',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 21,
    product: '2025 Topps Chrome F1 LogoFractor Mega Box',
    year: 2025,
    price: 569.95,
    priceDisplay: '$569.95',
    msrp: 550,
    seller: "Dave & Adam's Card World",
    url: 'https://www.dacardworld.com/sports-cards/2025-topps-chrome-f1-formula-1-logofractor-box',
    listingType: 'buy_now',
    availability: 'unknown',
    category: 'sealed_box',
    notes: 'Near MSRP ($569.95 vs $550 MSRP). Fanatics London Store exclusive at retail. Best identified US price.',
    source: "Dave & Adam's",
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 22,
    product: '2024 Topps Finest F1 Hobby Box',
    year: 2024,
    price: 450,
    priceDisplay: '~$450 (eBay avg)',
    msrp: 250,
    seller: 'eBay (secondary market)',
    url: 'https://www.ebay.com/sch/i.html?_nkw=2024+topps+finest+formula+1+hobby+box&LH_BIN=1',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Market avg $450. eBay range $353–$619. All retail sold out. Released April 2025.',
    source: 'eBay / SportsCardsPro',
    highlight: null,
    dateFound: '2026-03-14',
  },

  // ── PREMIUM SINGLES (Dynasty/Graded) ───────────────────────────────

  {
    id: 23,
    product: '2020 Dynasty F1 Lando Norris RC Patch Auto 10/10 BGS 9',
    year: 2020,
    price: 4321,
    priceDisplay: '$4,321',
    msrp: null,
    seller: 'Fanatics Collect',
    url: 'https://www.fanaticscollect.com/buy-now/cd63cfe7-6ab8-4f6d-91e6-267e4f842ed7/2020-topps-dynasty-formula-1-f1-lando-norris-rookie-patch-auto-1010-bgs-9-mint',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. #DAP-LN, serial 10/10. BGS 9 Mint — Pop 1 of 1, none higher. 2024 WDC Norris.',
    source: 'Fanatics Collect',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 24,
    product: '2020 Dynasty F1 Norris / Sainz Dual Relic Auto PSA 9 10/10',
    year: 2020,
    price: 13900,
    priceDisplay: '$13,900',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty-2020/products/pop1-psa-9-10-10-lando-norris-carlos-sainz-cdar-ns-team-dual-relic-auto-2020-topps-dynasty-f1',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Norris AND Sainz McLaren 2020. Serial 10/10. PSA 9, Pop 1 — none higher.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 25,
    product: '2020 Dynasty F1 Norris Single-Driver Dual Relic Auto PSA 9 09/10',
    year: 2020,
    price: 19900,
    priceDisplay: '$19,900',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty-2020/products/psa-9-09-10-lando-norris-sda-ln-dynasty-single-driver-dual-relic-autograph-2020-topps-dynasty-f1',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Dual patch relics from McLaren race suit. PSA 9. Norris 2024 WDC boosted values.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 26,
    product: '2020 Dynasty F1 Norris Triple Relic Auto PSA 9 2/10',
    year: 2020,
    price: 3490,
    priceDisplay: '$3,490 (sale from $3,690)',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty-2020',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Triple Relic Auto, 3 patch pieces. On sale. Past sales $5,100–$5,460.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 27,
    product: '2020 Dynasty F1 Norris Triple Relic Auto PSA 10&9 7/10',
    year: 2020,
    price: 3299,
    priceDisplay: '$3,299',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty-2020',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. PSA 10 card / PSA 9 auto sub-grades. Norris 2024 WDC premium.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 28,
    product: '2020 Dynasty F1 Norris Auto Patch Red 2/5',
    year: 2020,
    price: 5900,
    priceDisplay: '$5,900',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty-2020',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Red parallel (#/5) — second rarest after Gold 1/1. Ungraded.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 29,
    product: '2020 Dynasty F1 Charles Leclerc Auto Patch PSA 9 03/10',
    year: 2020,
    price: 11900,
    priceDisplay: '$11,900 (sale from $14,900)',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Leclerc #DAP-IICL. PSA 9. Prior sales ~$9,600. Ferrari premium.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 30,
    product: '2020 Dynasty F1 Charles Leclerc Dual Relic Auto PSA 9 /10',
    year: 2020,
    price: 3799,
    priceDisplay: '$3,799',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty-2020',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Entry point for Ferrari collectors. Prior Dual Relic Auto /10 sold $9,600 via Goldin.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },
  {
    id: 31,
    product: '2020 Dynasty F1 Verstappen / Albon Dual Relic Auto PSA 10 4/10',
    year: 2020,
    price: 17900,
    priceDisplay: '$17,900 (sale from $23,900)',
    msrp: null,
    seller: 'Authentics.gg',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'single',
    notes: 'ACTIVE. Verstappen AND Albon, Red Bull 2020. PSA 10 gem mint. Reduced from $23,900.',
    source: 'Authentics.gg',
    highlight: 'premium_single',
    dateFound: '2026-03-14',
  },

  // ── WATCH LIST (Sold Out / Monitor for Restocks) ───────────────────

  {
    id: 32,
    product: '2020 Topps Chrome F1 Sapphire Edition Hobby Box',
    year: 2020,
    price: 2195,
    priceDisplay: '$2,195 (was listed)',
    msrp: null,
    seller: 'BBC Exchange',
    url: 'https://bbcexchange.com/products/2020-topps-chrome-f1-formula-1-racing-sapphire-edition-box-hobby-8-4',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'Was $2,195 — excellent deal vs market $3,100. SOLD OUT. Monitor for restock.',
    source: 'BBC Exchange',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 33,
    product: '2020 Topps Chrome F1 Hobby Box',
    year: 2020,
    price: null,
    priceDisplay: 'Out of Stock',
    msrp: null,
    seller: "Dave & Adam's Card World",
    url: 'https://www.dacardworld.com/sports-cards/2020-topps-chrome-formula-1-racing-hobby-box',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'OOS. Check back for restocks. Market value ~$1,850. Free shipping over $199 when available.',
    source: "Dave & Adam's Card World",
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 34,
    product: '2020 Topps Chrome F1 Hobby Box',
    year: 2020,
    price: null,
    priceDisplay: 'Out of Stock',
    msrp: null,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2020-topps-chrome-formula-1-racing-hobby-box.html',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'OOS. Market value ~$1,850–$2,100. Monitor for restock.',
    source: 'Blowout Cards',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 35,
    product: '2024 Topps Chrome F1 Hobby Box',
    year: 2024,
    price: null,
    priceDisplay: 'Out of Stock',
    msrp: 240,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2024-topps-chrome-formula-1-f1-racing-hobby-box',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'OOS confirmed. Released Nov 2024.',
    source: 'Steel City Collectibles',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 36,
    product: '2024 Topps Finest F1 Hobby Box',
    year: 2024,
    price: 275,
    priceDisplay: '$275 (was listed)',
    msrp: 250,
    seller: 'World Champion Sports Cards',
    url: 'https://www.worldchampionsportscards.org/products/2024-topps-finest-f1-formula-1-hobby-box',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'SOLD OUT at $275 (was $300). Would have been near-MSRP. Market avg $450.',
    source: 'World Champion Sports Cards',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 37,
    product: '2024 Topps Paddock Pass F1 Hobby Box',
    year: 2024,
    price: 119.99,
    priceDisplay: '$119.99 (was listed)',
    msrp: 200,
    seller: 'F1 Official US Store',
    url: 'https://usf1store.formula1.com/en/formula-1-merchandise/2024-topps-paddock-pass-formula-1-factory-sealed-hobby-box/t-21106621+p-57880228155966+z-8-2568223584',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'Best deal found — $119.99 but OOS. True MSRP ~$125–$200. eBay avg ~$230.',
    source: 'Formula 1 Official US Store',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 38,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: 1199.99,
    priceDisplay: '$1,199.99 (was listed)',
    msrp: 1200,
    seller: 'Topps EQL',
    url: 'https://launches.topps.com/en-US/launch/2025-topps-dynasty-formula-1-hobby-box',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'Launched at MSRP. All retailers OOS. Community reports $7,500 case produced $15,000+ in hits.',
    source: 'Topps EQL',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 39,
    product: '2025 Topps Chrome F1 Sapphire Edition Hobby Box',
    year: 2025,
    price: 449.99,
    priceDisplay: '$449.99/box (was listed)',
    msrp: 500,
    seller: 'Topps EQL',
    url: 'https://launches.topps.com/en-US/launch/2025-topps-chrome-formula-1-sapphire-edition-hobby-box-sealed-case',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'Below MSRP at launch ($449.99/box in 10-box case). All units sold out.',
    source: 'Topps EQL',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 40,
    product: '2025 Topps Chrome F1 Value Box',
    year: 2025,
    price: 29.99,
    priceDisplay: '$29.99 (was listed)',
    msrp: 30,
    seller: 'Fanatics / F1 Official Store',
    url: 'https://www.fanatics.com/formula-1/formula-1-merchandise/2025-topps-chrome-formula-1-factory-sealed-value-box/o-9903+t-9909+p-203642169',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'MSRP value box, sold out online. Check Target, Walmart, Best Buy for in-store stock.',
    source: 'Fanatics',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },

  // ── CASES & MULTI-BOX DEALS ────────────────────────────────────────

  {
    id: 50,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4150,
    priceDisplay: '$4,149.95',
    msrp: 3000,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2025-topps-chrome-formula-1-racing-hobby-12-box-case.html',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'case',
    notes: 'Sale from $4,799.95 — save $650. 12 boxes = ~$346/box. Free shipping over $299. Best confirmed case price.',
    source: 'Blowout Cards',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 51,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4197,
    priceDisplay: '$4,197.00',
    msrp: 3000,
    seller: 'RbiCru7 Collectibles',
    url: 'https://rbicru7.com/products/2025-topps-chrome-formula-1-racing-hobby-12-box-case',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'case',
    notes: 'Only 1 available. 12 boxes = ~$350/box. Competitive with Blowout.',
    source: 'RbiCru7 Collectibles',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 52,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4200,
    priceDisplay: '$4,200.00',
    msrp: 3000,
    seller: 'eBay (casecentral25)',
    url: 'https://www.ebay.com/itm/188095129188',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'case',
    notes: 'Last one. Accepts Best Offer — may go lower. 12 boxes = $350/box before any offer.',
    source: 'eBay',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 53,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4380,
    priceDisplay: '$4,379.95',
    msrp: 3000,
    seller: 'eBay (blowoutcards)',
    url: 'https://www.ebay.com/itm/206051349740',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'case',
    notes: 'Official Blowout Cards eBay store. 12 boxes = ~$365/box.',
    source: 'eBay',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 54,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4428,
    priceDisplay: '$4,428.00',
    msrp: 3000,
    seller: 'eBay (joshodeezy)',
    url: 'https://www.ebay.com/itm/236597991475',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'case',
    notes: 'Ripped live option available. 12 boxes = ~$369/box.',
    source: 'eBay',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 55,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4568,
    priceDisplay: '$4,567.95',
    msrp: 3000,
    seller: 'eBay (midwestcards)',
    url: 'https://www.ebay.com/itm/116996467102',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'case',
    notes: 'Free returns. 12 boxes = ~$381/box.',
    source: 'eBay',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 56,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: null,
    priceDisplay: 'Sold Out',
    msrp: 3000,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2025-topps-chrome-formula-1-f1-racing-hobby-12-box-case',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'case',
    notes: 'OOS. 12 boxes per case. Monitor for restock.',
    source: 'Steel City Collectibles',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 57,
    product: '2025 Topps Chrome F1 Hobby 12-Box Case',
    year: 2025,
    price: 4700,
    priceDisplay: '$4,699.95',
    msrp: 3000,
    seller: 'Giant Sports Cards',
    url: 'https://www.giantsportscards.com/products/2025-topps-chrome-f1-formula-one-hobby-12-box-case',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'case',
    notes: 'OOS — email notification available for restock.',
    source: 'Giant Sports Cards',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },

  // ── 2025 DYNASTY F1 (Buy Multiple / Single Boxes) ──────────────────

  {
    id: 60,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: 3100,
    priceDisplay: '$3,099.95',
    msrp: 1200,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2025-topps-dynasty-formula-1-f1-racing-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'IN STOCK. Financing from $167/mo. PayPal available. Buy multiple boxes here — no quantity limit listed.',
    source: 'Steel City Collectibles',
    highlight: 'hot_deal',
    dateFound: '2026-03-14',
  },
  {
    id: 61,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: 3882,
    priceDisplay: '$3,882.49',
    msrp: 1200,
    seller: 'eBay (stargazer3715)',
    url: 'https://www.ebay.com/itm/267605870708',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'New listing. Accepts Best Offer — negotiate down. Ships from UK.',
    source: 'eBay',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 62,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: 4167,
    priceDisplay: '$4,167.21',
    msrp: 1200,
    seller: 'eBay (the-mall-88)',
    url: 'https://www.ebay.com/itm/198178396565',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Sealed. Accepts Best Offer. Ships from South Korea.',
    source: 'eBay',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 63,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: 4554,
    priceDisplay: '$4,554 (lowest ask)',
    msrp: 1200,
    seller: 'StockX',
    url: 'https://stockx.com/2025-topps-dynasty-f1-formula-1-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'Only 1 left at this price. Last sale $3,385. Make Offer available.',
    source: 'StockX',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 64,
    product: '2025 Topps Dynasty F1 Hobby 5-Box Case',
    year: 2025,
    price: null,
    priceDisplay: 'Sold Out',
    msrp: 6000,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2025-topps-dynasty-formula-1-racing-hobby-5-box-case-27270.html',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'case',
    notes: '5-box case — best value for multi-box Dynasty. All sold out. Monitor for restock.',
    source: 'Blowout Cards',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 65,
    product: '2025 Topps Dynasty F1 Hobby 5-Box Case',
    year: 2025,
    price: null,
    priceDisplay: 'Sold Out',
    msrp: 6000,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2025-topps-dynasty-formula-1-f1-racing-hobby-5-box-case',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'case',
    notes: '5-box case. OOS. Monitor for restock.',
    source: 'Steel City Collectibles',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 66,
    product: '2025 Topps Dynasty F1 Hobby 5-Box Case',
    year: 2025,
    price: 10000,
    priceDisplay: '$9,999.95',
    msrp: 6000,
    seller: 'Giant Sports Cards',
    url: 'https://www.giantsportscards.com/products/2025-topps-dynasty-formula-1-hobby-5-box-case',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'case',
    notes: 'Was $9,999.95 (was $10,999.95). OOS — email notification available.',
    source: 'Giant Sports Cards',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },
  {
    id: 67,
    product: '2025 Topps Dynasty F1 Hobby Box',
    year: 2025,
    price: null,
    priceDisplay: 'Sold Out',
    msrp: 1200,
    seller: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/2025-topps-dynasty-formula-1-racing-hobby-box.html',
    listingType: 'sold_out',
    availability: 'sold_out',
    category: 'sealed_box',
    notes: 'Single box OOS. Monitor for restock.',
    source: 'Blowout Cards',
    highlight: 'watch',
    dateFound: '2026-03-14',
  },

  // ── REFERENCE PRICING ──────────────────────────────────────────────

  {
    id: 41,
    product: '2020 Topps Chrome F1 Hobby Box',
    year: 2020,
    price: 1850,
    priceDisplay: '$1,850 (lowest ask)',
    msrp: null,
    seller: 'StockX',
    url: 'https://stockx.com/2020-topps-chrome-formula-1-racing-hobby-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'StockX lowest ask $1,850. Last sale $1,650. 12-month range $1,559–$1,743.',
    source: 'StockX',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 42,
    product: '2020 Topps Chrome F1 Sapphire Edition Hobby Box',
    year: 2020,
    price: 4000,
    priceDisplay: '$4,000 (Buy Now)',
    msrp: null,
    seller: 'StockX',
    url: 'https://stockx.com/2020-topps-topps-chrome-sapphire-formula-1-racing-box',
    listingType: 'buy_now',
    availability: 'in_stock',
    category: 'sealed_box',
    notes: 'StockX Buy Now $4,000. Last sale $3,000. Make Offer available. Market consensus ~$3,100.',
    source: 'StockX',
    highlight: null,
    dateFound: '2026-03-14',
  },
  {
    id: 43,
    product: '2020 Topps Chrome F1 Sapphire Edition Hobby Box',
    year: 2020,
    price: 3499.95,
    priceDisplay: '$3,499.95',
    msrp: null,
    seller: 'Steel City Collectibles',
    url: 'https://www.steelcitycollectibles.com/i/2020-topps-formula-1-f1-chrome-sapphire-edition-box',
    listingType: 'buy_now',
    availability: 'unknown',
    category: 'sealed_box',
    notes: 'Listed at $3,499.95. Availability not confirmed. Market avg ~$3,100.',
    source: 'Steel City Collectibles',
    highlight: null,
    dateFound: '2026-03-14',
  },
];

// ── Quick Links / Retailer Directory ─────────────────────────────────

export interface RetailerLink {
  name: string;
  url: string;
  description: string;
  icon: 'shopping' | 'auction' | 'graded' | 'live' | 'community';
}

export const retailerLinks: RetailerLink[] = [
  {
    name: 'eBay F1 Cards',
    url: 'https://www.ebay.com/sch/i.html?_nkw=topps+formula+1+hobby+box&LH_BIN=1',
    description: 'Buy It Now listings for Topps F1 hobby boxes',
    icon: 'auction',
  },
  {
    name: 'StockX F1',
    url: 'https://stockx.com/search?s=topps+formula+1',
    description: 'Verified marketplace with transparent pricing',
    icon: 'shopping',
  },
  {
    name: 'Blowout Cards',
    url: 'https://www.blowoutcards.com/trading-cards/formula-1-f1.html',
    description: 'Major retailer with frequent sales on F1 sealed',
    icon: 'shopping',
  },
  {
    name: "Dave & Adam's",
    url: 'https://www.dacardworld.com/sports-cards?q=formula+1',
    description: 'Wide F1 selection, $25 off coupon with sign-up',
    icon: 'shopping',
  },
  {
    name: 'Steel City',
    url: 'https://www.steelcitycollectibles.com/c/formula-1-f1-boxes',
    description: 'Competitive pricing, rewards program, free shipping $199+',
    icon: 'shopping',
  },
  {
    name: 'Fanatics Collect',
    url: 'https://www.fanaticscollect.com/search?q=formula+1',
    description: 'Marketplace for sealed & singles, verified by experts',
    icon: 'shopping',
  },
  {
    name: 'Authentics.gg (Dynasty)',
    url: 'https://www.authentics.gg/collections/f1-topps-dynasty',
    description: 'Premium graded Dynasty singles, vaulted & verified',
    icon: 'graded',
  },
  {
    name: 'MySlabs (Graded)',
    url: 'https://www.myslabs.com/bin/search/all?q=formula+1+topps',
    description: 'Fixed-price graded singles marketplace ($99–$15,000)',
    icon: 'graded',
  },
  {
    name: 'Whatnot (Live)',
    url: 'https://www.whatnot.com/category/trading-cards/formula-1',
    description: 'Live auction shows for F1 boxes & singles',
    icon: 'live',
  },
  {
    name: 'r/F1Cards',
    url: 'https://www.reddit.com/r/F1Cards/',
    description: 'Community deal posts, pricing discussion, where to buy',
    icon: 'community',
  },
];

// ── Helper functions ─────────────────────────────────────────────────

export function getPctVsMsrp(deal: Deal): number | null {
  if (deal.price == null || deal.msrp == null) return null;
  return Math.round(((deal.price - deal.msrp) / deal.msrp) * 100);
}

export function getHotDeals(): Deal[] {
  return deals.filter((d) => d.highlight === 'hot_deal');
}

export function getBelowMsrpDeals(): Deal[] {
  return deals.filter((d) => d.highlight === 'below_msrp');
}

export function getPremiumSingles(): Deal[] {
  return deals.filter((d) => d.highlight === 'premium_single');
}

export function getInStockBoxes(): Deal[] {
  return deals.filter(
    (d) =>
      d.availability === 'in_stock' &&
      d.category === 'sealed_box' &&
      d.highlight !== 'hot_deal' &&
      d.highlight !== 'below_msrp'
  );
}

export function getWatchList(): Deal[] {
  return deals.filter(
    (d) => d.highlight === 'watch' || d.highlight === 'sold_out'
  );
}

export function getCaseDeals(): Deal[] {
  return deals.filter((d) => d.category === 'case');
}

export function getCaseDealsInStock(): Deal[] {
  return deals.filter((d) => d.category === 'case' && d.availability === 'in_stock').sort((a, b) => (a.price || Infinity) - (b.price || Infinity));
}

export function getCaseDealsWatchlist(): Deal[] {
  return deals.filter((d) => d.category === 'case' && d.availability === 'sold_out');
}

export function getDynastyDeals(): Deal[] {
  return deals.filter(
    (d) => d.product.toLowerCase().includes('dynasty') && d.year === 2025
  ).sort((a, b) => (a.price || Infinity) - (b.price || Infinity));
}

export function getDynastyInStock(): Deal[] {
  return deals.filter(
    (d) => d.product.toLowerCase().includes('dynasty') && d.year === 2025 && d.availability === 'in_stock'
  ).sort((a, b) => (a.price || Infinity) - (b.price || Infinity));
}

export function getDynastyWatchlist(): Deal[] {
  return deals.filter(
    (d) => d.product.toLowerCase().includes('dynasty') && d.year === 2025 && d.availability === 'sold_out'
  );
}

export function getReferenceDeals(): Deal[] {
  return deals.filter(
    (d) =>
      d.highlight === null &&
      d.availability !== 'in_stock' &&
      d.category === 'sealed_box'
  );
}

// Find best available deal for a product (by year + productType match)
export function findBestDeal(year: number, productType: string): Deal | null {
  const normalizedType = productType.toLowerCase();
  const matching = deals.filter(d => {
    const dProduct = d.product.toLowerCase();
    return d.year === year
      && d.availability === 'in_stock'
      && d.price !== null
      && (
        (normalizedType === 'chrome' && dProduct.includes('chrome') && !dProduct.includes('sapphire') && !dProduct.includes('logofractor'))
        || (normalizedType === 'sapphire' && dProduct.includes('sapphire'))
        || (normalizedType === 'dynasty' && dProduct.includes('dynasty'))
        || (normalizedType === 'finest' && dProduct.includes('finest'))
        || (normalizedType === 'logofractor' && dProduct.includes('logofractor'))
        || (normalizedType === 'lights out' && dProduct.includes('lights out'))
        || (normalizedType === 'paddock pass' && dProduct.includes('paddock'))
      );
  });
  if (matching.length === 0) return null;
  return matching.sort((a, b) => (a.price || Infinity) - (b.price || Infinity))[0];
}

// Find ALL deals for a product (for watchlist detail)
export function findAllDeals(year: number, productType: string, format?: string): Deal[] {
  const normalizedType = productType.toLowerCase();
  return deals.filter(d => {
    const dProduct = d.product.toLowerCase();
    const yearMatch = d.year === year;
    const typeMatch = (
      (normalizedType === 'chrome' && dProduct.includes('chrome') && !dProduct.includes('sapphire') && !dProduct.includes('logofractor'))
      || (normalizedType === 'sapphire' && dProduct.includes('sapphire'))
      || (normalizedType === 'dynasty' && dProduct.includes('dynasty'))
      || (normalizedType === 'finest' && dProduct.includes('finest'))
      || (normalizedType === 'logofractor' && dProduct.includes('logofractor'))
      || (normalizedType === 'lights out' && dProduct.includes('lights out'))
      || (normalizedType === 'paddock pass' && dProduct.includes('paddock'))
    );
    // If format is specified (e.g. "Hobby Box"), match against deal product text
    const fmtMatch = !format || dProduct.includes(format.toLowerCase().replace(' box', ''));
    return yearMatch && typeMatch && fmtMatch;
  }).sort((a, b) => (a.price || Infinity) - (b.price || Infinity));
}
